# Site settings
title: Infrastructure Overload
email: jonathan.pigree@gmail.com
description: "A blog about my journey as an Infrastructure engineer"
baseurl: "/"
url: "https://infrastructureoverload.github.io"
github_username:  jpigree

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
plugins:
  - jekyll-feeds

